'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Search, ArrowUpRight } from 'lucide-react';
import { clienteService } from '@/services/clienteService';
import { processoService } from '@/services/processoService';
type Result = { name: string; detail: string; href: string };
const actions: Result[] = [{name:'Agenda e prazos',detail:'Ação rápida',href:'/prazos'},{name:'Analisar processo com IA',detail:'Ação rápida',href:'/gemini?acao=analisar_processo'},{name:'Preparar peça com IA',detail:'Ação rápida',href:'/gemini?acao=criar_peca'},{name:'Consultar CNJ',detail:'Ação rápida',href:'/datajud'}];
export function WorkspaceSearch() {
 const [query,setQuery]=useState(''),[open,setOpen]=useState(false),[results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(false);
 const root=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.current?.focus();input.current?.select();setOpen(true);}if(e.key==='Escape')setOpen(false);};const outside=(e:MouseEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};window.addEventListener('keydown',key);document.addEventListener('mousedown',outside);return()=>{window.removeEventListener('keydown',key);document.removeEventListener('mousedown',outside);};},[]);
 useEffect(()=>{if(!open||query.trim().length<2)return;let active=true;const timer=setTimeout(async()=>{const rows=await Promise.allSettled([clienteService.getAll(),processoService.getAll()]);if(!active)return;const term=query.trim().toLocaleLowerCase('pt-BR');const clients=rows[0].status==='fulfilled'?rows[0].value.filter(c=>c.nome.toLocaleLowerCase('pt-BR').includes(term)).slice(0,4).map(c=>({name:c.nome,detail:'Cliente',href:`/clientes?q=${encodeURIComponent(c.nome)}`})):[];const processes=rows[1].status==='fulfilled'?rows[1].value.filter(p=>`${p.numero_processo} ${p.titulo} ${p.cliente?.nome||''}`.toLocaleLowerCase('pt-BR').includes(term)).slice(0,4).map(p=>({name:p.titulo||p.numero_processo,detail:`Processo · ${p.numero_processo}`,href:`/processos?q=${encodeURIComponent(p.numero_processo)}`})):[];setResults([...processes,...clients]);setLoading(false);setError(rows.some(r=>r.status==='rejected'));},300);return()=>{active=false;clearTimeout(timer);};},[query,open]);
 const searching=query.trim().length>=2;
 const quick=actions.filter(a=>a.name.toLocaleLowerCase('pt-BR').includes(query.trim().toLocaleLowerCase('pt-BR')));
 return <div ref={root} className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" aria-hidden/><input ref={input} value={query} onChange={e=>{setQuery(e.target.value);setResults([]);setError(false);setLoading(e.target.value.trim().length>=2);}} onFocus={()=>setOpen(true)} aria-label="Buscar clientes, processos e ações" aria-controls="workspace-search-results" placeholder="Buscar clientes, processos e ações..." className="w-full rounded-lg border border-line bg-slate-50 py-2.5 pl-9 pr-16 text-sm focus:outline-none focus:ring-2 focus:ring-brand/30 dark:bg-white/5"/><kbd aria-hidden className="pointer-events-none absolute right-3 top-3 hidden rounded border border-line px-1 text-xs text-slate-500 sm:block">Ctrl K</kbd>{open&&<div id="workspace-search-results" className="search-results absolute left-0 right-0 top-full z-50 mt-2 max-h-[65vh] overflow-y-auto rounded-xl border border-line bg-white p-2 shadow-xl dark:bg-slate-900"><p className="px-3 py-2 text-xs font-semibold text-slate-500">{searching?'Clientes e processos':'Ações rápidas'}</p>{searching&&<p role="status" className="px-3 py-2 text-xs text-slate-500">{loading?'Buscando...':error?'Parte dos resultados está indisponível.':results.length===0?'Nenhum cliente ou processo encontrado.':null}</p>}{[...(searching?results:[]),...quick].map(r=><Link key={r.href} href={r.href} onClick={()=>setOpen(false)} className="search-result"><span className="min-w-0"><span className="block truncate text-sm font-medium">{r.name}</span><span className="block truncate text-xs text-slate-500">{r.detail}</span></span><ArrowUpRight className="h-4 w-4 shrink-0" aria-hidden/></Link>)}</div>}</div>;
}
