-- AlterTable
ALTER TABLE "Prazo" ADD COLUMN IF NOT EXISTS "hora" VARCHAR(10) NOT NULL DEFAULT '09:00';
ALTER TABLE "Prazo" ADD COLUMN IF NOT EXISTS "tipoCompromisso" VARCHAR(50) NOT NULL DEFAULT 'Prazo Fatal';
ALTER TABLE "Prazo" ADD COLUMN IF NOT EXISTS "responsavel" VARCHAR(100);
